spring.application.name=expensetracker

server.port=8080

spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.default-property-inclusion=non_null

expense.storage.file=data/expenses.json